services:
  genbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandrro/genbuilder:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    gpus: all
